name: tox

on:
  push:
  pull_request:

jobs:
 python:
   runs-on: ubuntu-latest
   strategy:
     matrix:
       python: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]
       include:
         - python: "3.7"
           env: py37
         - python: "3.8"
           env: py38
         - python: "3.9"
           env: py39
         - python: "3.10"
           env: py310
         - python: "3.11"
           env: py311
         - python: "3.12"
           env: py312
   continue-on-error: true
   steps:
     - name: Checkout
       uses: actions/checkout@v2.2.0
       with:
         submodules: recursive
     - name: Setup Python
       uses: actions/setup-python@v2
       with:
         python-version: ${{ matrix.python }}
     - name: Install Tox and other packages
       run: |
         pip install --upgrade pip
         pip install tox
     - name: Install netcdf tools
       run: |
         sudo apt-get update
         sudo apt-get -qq install netcdf-bin
     - name: Run Tox
       run: tox -e ${{ matrix.env }}
